version: '3'

services:
  docs-site:
    build:
      context: ./docs-site
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./docs:/app/docs
      - ./sql-content:/app/sql-content:ro
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - sql-docs-network

  ai-inference:
    build:
      context: ./ai-inference
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./sql-content:/app/sql-content:ro
      - ai-vectorstore:/app/vectorstore
    env_file:
      - ./ai-inference/.env
    restart: unless-stopped
    networks:
      - sql-docs-network

volumes:
  ai-vectorstore:
    driver: local

networks:
  sql-docs-network:
    driver: bridge 